[package]
name = "rvkr"
version = "0.1.0"
authors = ["Brennan Shacklett <bpshacklett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.29"
glfw = "0.34"
emplace_proc = { path = "emplace_proc" }
